[package]
name = "uint-fuzz"
description = "Fuzzers for uint algorithms"
readme = "README.md"
publish = false
version = "0.1.0"
rust-version = "1.56.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
uint = { workspace = true, default-features = true }
libfuzzer-sys = { workspace = true }
rug = { workspace = true, default-features = true, features = ["integer"] }

[[bin]]
name = "div_mod"
path = "fuzz_targets/div_mod.rs"

[[bin]]
name = "div_mod_word"
path = "fuzz_targets/div_mod_word.rs"

[[bin]]
name = "isqrt"
path = "fuzz_targets/isqrt.rs"
