[package]
name = "impl-borsh"
version = "0.1.0"
authors = ["Steven Sloboda <steven@eclipse.builders>"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/paritytech/parity-common"
description = "Borsh serialization support for uint and fixed hash."
edition = "2021"
rust-version = "1.56.1"

[features]
default = ["std",]
std = ["borsh/std"]

[dependencies]
borsh = { version = "0.9.3", default-features = false, features = ["std"] }
