[package]
name = "kvdb-test-utils"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Common testing utilities for `KeyValueDB` implementations."
license = "GPL-3.0"

[dependencies]
kvdb = { path = "../kvdb", version = "0.2" }
